### Create a new user
POST http://localhost:3000/auth/signup
content-Type: application/json

{
  "email": "user@mail.com",
  "password": "pass12345"
}

### SignIn
POST http://localhost:3000/auth/signin
content-Type: application/json

{
  "email": "user@mail.com",
  "password": "pass12345"
}

### SignOut
POST http://localhost:3000/auth/signout

### Get current user
GET http://localhost:3000/auth/current


### Find a particular user
GET http://localhost:3000/auth/1

### Find all users by email
GET http://localhost:3000/auth?email=user@mail.com

### Remove user
DELETE http://localhost:3000/auth/5

### Update user
PATCH http://localhost:3000/auth/1
content-Type: application/json

{
  "password": "user@mail.com"
}

